### PR TITLE
Use explicit imports instead of star imports for generated types

### LINKED ISSUE #176: Compilation of generated files fails if data model object has `Byte`
If you try and generate an API for object that contains a Byte, the generated files to do not compile. Any generated files that to try reference the type (eg <APIName>HashIndex.java) conflict between my.generated.package.Byte and java.lang.Byte, since we import my.generated.*.

A couple ways to fix this:
* have similar treatment for Byte as we do for String, Integer, etc (include them in com.netflix.hollow.core.type and replace with HByte) #172
* import the generated Byte classes directly, instead of using a star import (WIP)

### PR DESCRIPTION
**Pull request by akhaku**
For cases where our generated type matches a java.lang type
(eg Byte), using a star import causes the compiler to get
confused between the generated type and the java.lang type.
Switching to explicit imports makes it clear to the
compiler, so do that.
Fixes #176.

### CODE REVIEW

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 1]
```diff
@@ -82,4 +137,17 @@ private String createFullPackageName(String packageName, String subPackageName,
...
     }
+
+    private void appendImportFromBasePackage(StringBuilder builder, String leaf) {
+        builder.append("import ").append(packageName).append(".").append(leaf)
+            .append(";\n");
+    }
+
+    private void addToSetIfNotPrimitive(Set<String> set, String... schemaNames) {
+        for (String schemaName : schemaNames) {
+            if (!HollowCodeGenerationUtils.isPrimitiveType(schemaName)) {
```
Comment (akhaku) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: I initially checked `!config.isUseHollowPrimitiveTypes() || ` here, assuming that isUseHollowPrimitiveTypes being `false` meant that we were generating even primitive types, but the tests failed 😕

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 2]
```diff
@@ -30,14 +40,15 @@
     protected String className;
     protected boolean useCollectionsImport=false;
 
-    public HollowConsumerJavaFileGenerator(String packageName, String subPackageName, CodeGeneratorConfig config) {
+    public HollowConsumerJavaFileGenerator(String packageName, String subPackageName,
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: I assume this is auto formatting.   If so, it would be best only to auto format on lines that were changed.  This way it will minimize diff change noises ;)

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 3]
```diff
@@ -63,9 +85,42 @@ protected void appendPackageAndCommonImports(StringBuilder builder) {
...
+                            HollowMapSchema mapSchema = (HollowMapSchema) schema;
+                            addToSetIfNotPrimitive(imports, mapSchema.getKeyType(),
+                                    mapSchema.getValueType());
+                            break;
+                        default:
+                            throw new IllegalArgumentException(
+                                    "Unexpected HollowSchema to import: " + schema);
+
+                    }
+                    for (String anImport : imports) {
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Not sure if I am reading this correctly, but should this be outside of the for(HollowSchema) loop?

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java (hunk 2 above)
Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Oops, will revert, thanks!

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java (hunk 3 above)
Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Ahh you're right, this is incorrectly inside the for loop. Probably resulted in extra imports, which I didn't notice :/

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 4]
```diff
@@ -82,4 +137,17 @@ private String createFullPackageName(String packageName, String subPackageName,
     private boolean isEmpty(String value) {
         return value == null || value.trim().isEmpty();
     }
+
+    private void appendImportFromBasePackage(StringBuilder builder, String leaf) {
+        builder.append("import ").append(packageName).append(".").append(leaf)
+            .append(";\n");
+    }
+
+    private void addToSetIfNotPrimitive(Set<String> set, String... schemaNames) {
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Minor since this is a small method but it might be better to rename "set" to importSet or something more descriptive ;)

Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Can't hurt, will do

Comment (davesu) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Actually, I am not clear on this method.  is it supposed to convert schemaName into Hollow Package Import String?

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 5]
```diff
@@ -63,9 +85,42 @@ protected void appendPackageAndCommonImports(StringBuilder builder) {
             }
 
             if (config.isUsePackageGrouping()) {
-                builder.append("import ").append(packageName).append(".*;\n");
-                builder.append("import ").append(packageName).append(".core.*;\n");
-                if (useCollectionsImport) builder.append("import ").append(packageName).append(".collections.*;\n\n");
+                if (apiClassname != null) {
+                    appendImportFromBasePackage(builder, apiClassname);
+                }
+                Set<String> imports = new HashSet<>();
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Perhaps rename "imports" to schemaNameSet since I thought that contains the full import strings.  Perhaps it was just me ;)

Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: Ah, yes, will do.

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 6]
```diff
@@ -82,4 +136,23 @@ private String createFullPackageName(String packageName, String subPackageName,
     private boolean isEmpty(String value) {
         return value == null || value.trim().isEmpty();
     }
+
+    private void appendImportFromBasePackage(StringBuilder builder, String leaf) {
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java:140]: Do we need to make sure the firstChar of the leaf is upper case?  

I believe the Code generator upper case the first char of the schema name.

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 7]
```diff
@@ -63,9 +84,42 @@ protected void appendPackageAndCommonImports(StringBuilder builder) {
...
+                                    "Unexpected HollowSchema to import: " + schema);
+
+                    }
+                }
+                for (String schemaName : schemaNameSet) {
+                    appendImportFromBasePackage(builder, schemaName);
+                }
+                appendImportFromBasePackage(builder, "core.*");
+                if (useCollectionsImport) {
+                    appendImportFromBasePackage(builder, "collections.*\n");
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: looks like it has extra "\n".

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java [hunk 8]
```diff
@@ -82,4 +136,23 @@ private String createFullPackageName(String packageName, String subPackageName,
     private boolean isEmpty(String value) {
         return value == null || value.trim().isEmpty();
     }
+
+    private void appendImportFromBasePackage(StringBuilder builder, String leaf) {
+        builder.append("import ").append(packageName).append(".").append(leaf)
+            .append(";\n");
```
Comment (davesu) [inline hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: minor but it seems like your line wrap is a bit aggressive.  Perhaps in the future it would be nice to be a bit more lenient ;)

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java (hunk 6 above)
Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java:140]: The schema name comes in cased correctly in my testing. Also, we can't do it here, since we pass in things like `core.*` and `collections.*` to this method (see :118 and :120)

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java (hunk 7 above)
Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: indeed, fixing

File: hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java (hunk 8 above)
Comment (akhaku) [reply hollow/src/main/java/com/netflix/hollow/api/codegen/HollowConsumerJavaFileGenerator.java]: yeah, I've been wrapping at 90 for a few years, a little more difficult with 4 space indents, though

**Review by ghost — APPROVED** [review]

**Comment by akhaku** [comment]
Squashed commits, merging after build passes.
