### PR TITLE
Better HashIndex behavior with null fields

### LINKED ISSUE #128: Add ability to use a hash index on nullable fields
When creating a hash index on a nullable field, `ArrayOutOfBoundsException` is thrown from `FixedLengthElementArray:94`.

### PR DESCRIPTION
**Pull request by ghost**
* [x] fix exception when building index over fields with null values
* [ ] ~~fix exception when attempting to find matches with null query value~~
* [x] more meaningful exception when attempting to find matches with null query values

Fixes #128.

### CODE REVIEW

File: hollow/src/main/java/com/netflix/hollow/core/index/HollowHashIndex.java [hunk 1]
```diff
@@ -158,6 +158,8 @@ private boolean matchIsEqual(FixedLengthElementArray matchHashTable, long hashBu
 
                 HollowObjectTypeReadState objectAccess = (HollowObjectTypeReadState)readState;
                 int fieldIdx = fieldPath[fieldPath.length-1];
+                if(hashOrdinal == -1 && query[i] == null)
```
Comment (ghost) [inline hollow/src/main/java/com/netflix/hollow/core/index/HollowHashIndex.java:163]: Possibly belongs in `HollowReadFieldUtils.fieldValueEquals` instead.

**Comment by ghost** [comment]
The changes I made for allowing `findMatches` with null query values doesn't cover all cases. Instead of trying to add that as part of this PR, I'm going to instead have a better exception that querying for null isn't supported.
